What is Pandas?

Pandas is a Python library used for working with data. It helps you load, clean, organize, analyze, and manipulate data easily.

Think of Pandas like Excel inside Python, but much more powerful.

For example:

Excel	                  Pandas
Rows & Columns	          Rows & Columns
Filter data	              Filter data
Sort	                  Sort
Formulas	              Calculations
Pivot Table 	          Grouping/Aggregation
Cleaning duplicates	      Data cleaning

Why do Data Analysts use Pandas?

As a data analyst, most of your work is:

Collecting data
Cleaning messy data
Analyzing data
Finding insights
Making reports

Main Uses of Pandas in a Data Analyst Role
1. Reading Data Files

Most companies store data in files like:

CSV /
Excel /
SQL databases /
JSON

Pandas can read them easily.

In [8]:
import pandas as pd

data = pd.read_csv(r"D:\Narendra\Employee_Complete_Dataset.csv")
data

,Employee_number,Employee_name,Employee_age,Maritial_Status,Current_Salary,Number_of_Children,years_experience,past_projects,current_projects,Divorced_earlier,Father_alive,Mother_alive,performance_rating,Education_level,Department,Role,Job_Satisfaction,Work_Life_Balance,is_outlier
0,10001,Karen Anderson,36,True,116138,2,12,6,1,No,Yes,Yes,3,Bachelor's,R&D,Researcher,10.000000,1.936454,0
1,10002,David Taylor,34,False,82171,3,10,5,0,Yes,Yes,No,5,Diploma,HR,HR Executive,10.000000,4.077728,0
2,10003,Nina Kumar,36,False,48600,1,0,2,3,Yes,Yes,Yes,4,Diploma,Sales,Sales Manager,10.000000,3.975622,0
3,10004,John Patel,42,True,39675,1,2,4,2,Yes,Yes,Yes,3,Diploma,Engineering,Software Engineer,1.000000,3.790951,0
4,10005,Emily Sharma,27,True,161304,3,3,11,2,Yes,Yes,Yes,2,High School,R&D,Scientist,8.251833,10.000000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,59996,Olivia Singh,34,True,30000,1,10,8,2,No,No,Yes,3,Diploma,Support,Customer Specialist,1.620645,10.000000,0
49996,59997,Rohit Anderson,63,False,39817,0,30,5,1,Yes,Yes,Yes,2,Bachelor's,Support,Support Engineer,9.653380,1.826064,0
49997,59998,Olivia Taylor,39,True,30000,0,12,8,3,No,Yes,Yes,2,Diploma,Engineering,ML Engineer,4.690698,2.470172,0
49998,59999,Luke Brown,40,True,50384,1,7,3,2,No,Yes,Yes,3,Bachelor's,Finance,Senior Analyst,1.031014,2.462067,0
49999,60000,Arun Thomas,42,False,115609,2,19,4,1,No,No,Yes,5,Bachelor's,Support,Customer Specialist,8.571629,2.912378,0

1. Series in Pandas

A Series is a single column of data.

Think of it like one column in Excel.

Example:

In [9]:
s = pd.Series([10, 20, 30, 40])

s

0    10
1    20
2    30
3    40
dtype: int64

Easy Understanding:

Imagine marks of students:

Marks
10
20
30
40

This single column = Series

Remember:
Series = One Column

2. DataFrame in Pandas

A DataFrame is a table with rows and columns.

Think of it like an Excel sheet.

Example:

In [10]:
data = {
    "Name": ["Ram", "Sam", "John"],
    "Age": [22, 24, 21]
}

df = pd.DataFrame(data)

df

   Name  Age
0   Ram   22
1   Sam   24
2  John   21

Easy Understanding:
Name	Age
Ram	    22
Sam	    24
John	21

This whole table = DataFrame

Remember:
DataFrame = Full Table

3. Add Another Column

Suppose we want to add Marks column.

Existing Data:

Name	Age
Ram	    22
Sam	    24

Add new column:

In [15]:
df["Marks"] = [80, 90, 100]

df

   Name  Age  Marks
0   Ram   22     80
1   Sam   24     90
2  John   21    100

Easy Formula: df["New Column"] = values

Example:

df["City"] = ["Chennai", "Coimbatore"]